import{S as p,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function y(i){const n=`https://pixabay.com/api/?key=47358602-d5490533da2bc88f2f38f5bcb&q=${encodeURIComponent(i)}&image_type=photo&orientation=horizontal&safesearch=true&page=1`;return fetch(n).then(e=>{if(!e.ok)throw new Error("Failed to fetch images");return e.json()}).then(e=>e).catch(e=>{console.error(e)})}let a;const u=document.querySelector(".gallery"),f=document.querySelector(".loader");function g(i){const r=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:s,comments:m,downloads:d})=>`<li class="gallery-list-item">
        <a href="${n}" class="gallery-list-link">
          <img class="gallery-img" src="${o}" alt="${e}" />
        </a>
        <div class="img-info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${m}</p>
          <p><b>Downloads:</b> ${d}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",r),a?a.refresh():a=new p(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function h(){u.innerHTML=""}function b(){f.classList.add("active")}function l(){f.classList.remove("active")}const L=document.querySelector(".form");document.querySelector(".gallery");document.querySelector(".loader");const S=document.querySelector('input[name="search-text"]');L.addEventListener("submit",i=>{i.preventDefault();const r=S.value.trim();r&&(h(),b(),y(r).then(o=>{if(l(),o.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3});return}g(o.hits)}).catch(o=>{l(),c.error({title:"Error",message:"Oops! Something went wrong. Please try again later.",position:"topRight",timeout:5e3}),console.error(o)}))});
//# sourceMappingURL=index.js.map
