import{a as f,S as g,i as c}from"./assets/vendor-1AYLTIiv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function y(i){const r="https://pixabay.com/api/",s={key:"47358602-d5490533da2bc88f2f38f5bcb",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:1};return f.get(r,{params:s}).then(e=>e.data).cetch(e=>{throw console.log(e.message),e})}let a;const u=document.querySelector(".gallery"),m=document.querySelector(".loader");function h(i){const r=i.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:n,comments:p,downloads:d})=>`<li class="gallery-list-item">
        <a href="${s}" class="gallery-list-link">
          <img class="gallery-img" src="${o}" alt="${e}" />
        </a>
        <div class="img-info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${p}</p>
          <p><b>Downloads:</b> ${d}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",r),a?a.refresh():a=new g(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function b(){u.innerHTML=""}function L(){m.classList.add("active")}function l(){m.classList.remove("active")}const S=document.querySelector(".form");document.querySelector(".gallery");document.querySelector(".loader");const q=document.querySelector('input[name="search-text"]');S.addEventListener("submit",i=>{i.preventDefault();const r=q.value.trim();r&&(b(),L(),y(r).then(o=>{if(l(),o.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3});return}h(o.hits)}).catch(o=>{l(),c.error({title:"Error",message:"Oops! Something went wrong. Please try again later.",position:"topRight",timeout:5e3}),console.error(o)}))});
//# sourceMappingURL=index.js.map
